# Generated by Django 4.0.7 on 2023-07-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_comapny_id_company_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
