# Generated by Django 4.0.7 on 2023-07-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_employee_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
    ]
