# Generated by Django 4.0.7 on 2023-07-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_employee_company'),
    ]

    operations = [
    ]
